from __future__ import annotations

from collections import Counter
import csv
import importlib.metadata
import json
from pathlib import Path
import platform
import shutil
import subprocess

import pandas as pd
import torch

from .event_openworld_data import attach_input_groups
from .model_functions.zero_shot import require_cuda
from .study_state import atomic_json, environment_metadata, file_sha256, utc_now
from .zero_shot_data import INPUT_COLUMNS


def audit_local_data(data_path: Path) -> dict[str, object]:
    frame = attach_input_groups(pd.read_csv(data_path))
    counts = frame.groupby("_input_group", sort=False).size()
    conflicts = frame.groupby("_input_group", sort=False)["Class"].nunique()
    return {
        "schema_version": 1,
        "audited_utc": utc_now(),
        "path": str(data_path.resolve()),
        "sha256": file_sha256(data_path),
        "rows": len(frame),
        "exact_input_groups": int(frame["_input_group"].nunique()),
        "duplicate_rows_beyond_first": int(len(frame) - frame["_input_group"].nunique()),
        "duplicate_groups": int((counts > 1).sum()),
        "maximum_group_size": int(counts.max()),
        "conflicting_label_groups": int((conflicts > 1).sum()),
        "class_rows": {str(int(k)): int(v) for k, v in frame["Class"].value_counts().sort_index().items()},
        "class_unique_groups": {str(int(k)): int(v) for k, v in frame.drop_duplicates("_input_group")["Class"].value_counts().sort_index().items()},
        "features": INPUT_COLUMNS,
        "analysis_unit": "one representative row per exact-input SHA-256 group",
    }


def audit_environment(root: Path, device_string: str = "cuda:0") -> dict[str, object]:
    device = require_cuda(device_string)
    payload = environment_metadata(device)
    free_bytes, runtime_total_bytes = torch.cuda.mem_get_info(device)
    try:
        driver = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"], text=True, timeout=10
        ).strip().splitlines()[0]
    except (OSError, subprocess.SubprocessError, IndexError):
        driver = None
    payload.update({
        "schema_version": 1,
        "audited_utc": utc_now(),
        "python_executable_note": "Record generated by the interpreter running this command.",
        "nvidia_driver": driver,
        "cuda_available": torch.cuda.is_available(),
        "cuda_bf16_supported": torch.cuda.is_bf16_supported(),
        "gpu_free_memory_bytes_at_audit": int(free_bytes),
        "gpu_runtime_total_memory_bytes": int(runtime_total_bytes),
        "disk_free_bytes": shutil.disk_usage(root).free,
    })
    for package in ("otdrs", "pydantic", "click"):
        try:
            payload.setdefault("packages", {})[package] = importlib.metadata.version(package)
        except importlib.metadata.PackageNotFoundError:
            payload.setdefault("packages", {})[package] = None
    return payload


def _sor_metadata(path: Path) -> dict[str, object]:
    import otdrs

    trace = otdrs.parse_file(str(path))
    scale = trace.data_points.scale_factors[0]
    key_events = list(trace.key_events.key_events) + [trace.key_events.last_key_event]
    return {
        "path": path.as_posix(),
        "sha256": file_sha256(path),
        "points": int(trace.data_points.number_of_data_points),
        "scale_factor": int(scale.scale_factor),
        "wavelength_nm": int(trace.general_parameters.nominal_wavelength),
        "pulse_width_ns": [int(value) for value in trace.fixed_parameters.pulse_widths_used],
        "averaging_time_s": int(trace.fixed_parameters.averaging_time),
        "event_count": int(trace.key_events.number_of_key_events),
        "event_codes": [event.event_code for event in key_events],
        "event_propagation_times": [int(event.event_propogation_time) for event in key_events],
    }


def audit_external_dataset(external_root: Path, archive_path: Path) -> dict[str, object]:
    sor_files = sorted(external_root.rglob("*.sor"))
    tsv_files = sorted(external_root.rglob("*.tsv"))
    sor_rows: list[dict[str, object]] = []
    failures: list[dict[str, str]] = []
    for path in sor_files:
        try:
            row = _sor_metadata(path)
            row["path"] = str(path.relative_to(external_root).as_posix())
            sor_rows.append(row)
        except Exception as exc:  # recorded rather than silently discarded
            failures.append({"path": str(path.relative_to(external_root).as_posix()), "error": f"{type(exc).__name__}: {exc}"})
    tsv_schema: dict[str, dict[str, object]] = {}
    for path in tsv_files:
        key = path.parent.name
        entry = tsv_schema.setdefault(key, {"files": 0, "rows": 0, "column_counts": Counter(), "third_field_examples": Counter()})
        entry["files"] += 1
        with path.open("r", encoding="utf-8", newline="") as handle:
            for row in csv.reader(handle, delimiter="\t"):
                entry["rows"] += 1
                entry["column_counts"][str(len(row))] += 1
                if len(row) >= 3:
                    entry["third_field_examples"][row[2]] += 1
    for entry in tsv_schema.values():
        entry["column_counts"] = dict(entry["column_counts"])
        entry["third_field_examples"] = dict(entry["third_field_examples"].most_common(30))
    extracted_hash = __import__("hashlib").sha256()
    for path in sorted([*sor_files, *tsv_files]):
        extracted_hash.update(path.relative_to(external_root).as_posix().encode())
        extracted_hash.update(bytes.fromhex(file_sha256(path)))
    return {
        "schema_version": 1,
        "audited_utc": utc_now(),
        "source": "https://www.kaggle.com/datasets/johannesreber/otdr-trace-training-data",
        "source_doi": "10.1364/JOCN.516659",
        "license": "CC BY-NC-SA 4.0 (dataset card)",
        "selection_use": "prohibited",
        "archive": {"path": str(archive_path.resolve()), "bytes": archive_path.stat().st_size, "sha256": file_sha256(archive_path)},
        "extracted_root": str(external_root.resolve()),
        "extracted_file_count": len(sor_files) + len(tsv_files),
        "extracted_manifest_sha256": extracted_hash.hexdigest(),
        "measured_sor_count": len(sor_files),
        "measured_sor_parsed": len(sor_rows),
        "measured_sor_failures": failures,
        "measured_sor": sor_rows,
        "simulated_tsv_count": len(tsv_files),
        "tsv_schema": tsv_schema,
        "label_policy": "Do not map external event labels into local classes 1..7.",
    }


def write_initial_audits(study_root: Path, data_path: Path, device: str = "cuda:0") -> None:
    external_root = study_root / "external" / "dataset"
    archive = study_root / "external" / "otdr-trace-training-data.zip"
    atomic_json(study_root / "DATA_AUDIT.json", audit_local_data(data_path))
    atomic_json(study_root / "ENVIRONMENT.json", audit_environment(study_root, device))
    atomic_json(study_root / "external" / "manifest.json", audit_external_dataset(external_root, archive))


if __name__ == "__main__":
    otdr_root = Path(__file__).resolve().parents[1]
    write_initial_audits(
        otdr_root / "experiments" / "otdr_event_openworld_study",
        otdr_root / "src" / "data" / "OTDR_DATA.csv",
    )
